name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install git linuxbrew-wrapper
      - run: brew install coreutils
      #- run: cargo install mdbook
      - run: chmod 777 -R ./
      - run: make github_pages

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: kumakichi/kumakichi.github.io
          publish_branch: master
          publish_dir: ./book
          destination_dir: easy_rust_chs
